"""empty message

Revision ID: 72c12b41582d
Revises: 
Create Date: 2024-07-30 16:25:58.640200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c12b41582d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=100), nullable=False),
    sa.Column('customer_address', sa.String(length=200), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_delivery', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('allergies_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['allergies_id'], ['allergies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('image_url_1', sa.String(), nullable=False),
    sa.Column('image_url_2', sa.String(), nullable=False),
    sa.Column('ingredient_1_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_2_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_3_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_4_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_5_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_6_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_7_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_8_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_9_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_10_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_10_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_1_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_2_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_3_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_4_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_5_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_6_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_7_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_8_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_9_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('ingredients')
    op.drop_table('user')
    op.drop_table('suppliers')
    op.drop_table('order')
    op.drop_table('allergies')
    op.drop_table('admins')
    # ### end Alembic commands ###
